# Generated by Django 5.1.6 on 2025-02-19 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='cod',
            field=models.CharField(blank=True, max_length=100, null=True, unique=True),
        ),
        migrations.AddField(
            model_name='customuser',
            name='email_confirmat',
            field=models.BooleanField(default=False),
        ),
    ]
