# Generated by Django 5.1.6 on 2025-02-19 16:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aplicatie_exemplu', '0003_promotie_vizualizare'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='vizualizare',
            options={'ordering': ['-data_vizualizare'], 'verbose_name': 'Vizualizare', 'verbose_name_plural': 'Views'},
        ),
        migrations.AddField(
            model_name='vizualizare',
            name='numar_vizualizari',
            field=models.IntegerField(default=1),
        ),
    ]
